name: Flask App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Add commands to run your tests here
        python -m unittest discover

    - name: Start Flask app
      run: |
        export FLASK_APP=routes.py
        export FLASK_ENV=development
        flask run --host=0.0.0.0 &

    - name: Test Flask app
      run: |
        sleep 10  # Give time for Flask to start
        curl -v http://localhost:5000

    - name: Deploy to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: app/templates   # Adjust to the directory where your Flask app files are
